### ISSUE TITLE
Support django admin light/dark theme switcher

### ISSUE THREAD

**Issue by x0nix** [django-mptt/django-mptt#826]
Django 4.2 admin adds theme switcher.

When
- my browser sets prefers-color-scheme: dark
- i switch back to light

Then drag and collapsed handle are (almost) invisible.

Like this:
![](https://user-images.githubusercontent.com/75339002/131719902-16390b18-597c-407f-897f-06dfaa6d8fc5.png)

**Comment by Zerotask** [comment]
I also stumbled upon this when I added django-jet-reboot. The actions and the row background-color are both white now. I only see the actions, if I select a row.

I noticed, that this is because of a media selector:
```css
@media (prefers-color-scheme: dark) {
  .tree-node.children {
    background-image: url(disclosure-down-white.png);
  }
  .tree-node.closed {
    background-image: url(disclosure-right-white.png);
  }
  .drag-handle {
    background-image: url(arrow-move-white.png);
  }

  #result_list tbody tr:focus {
    background-color: var(--selected-row, #00363a) !important;
    outline: 0px;
  }
}
```

and I have set dark theme in my OS.

Therefore a possible solution could be a new setting to deactivate this behavior?
